# -*- coding: utf-8 -*-
"""S16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUO0kuCqtBdfVLRwXFeRneVPIPv8jlva

## Nota:

Primero, si ya tienes spark ejecutado la sesión sesión de spark, reinicia el entorno; en colab usa "entorno de ejecución" y "reiniciar.

Posteriormente instala delta lake.
"""

# Instalar delta lake

!pip install -q delta-spark

# Llamado de modulos

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from delta import configure_spark_with_delta_pip

# Crear sesión de spark con configuración para Delta Lake

builder = (
    SparkSession.builder
    .appName("Delta_Lake")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
)

spark = configure_spark_with_delta_pip(builder).getOrCreate()

# Lectura de datos
Flight_csv = spark.read.csv(
    "/content/drive/MyDrive/flight data.csv",
    header = True,
    inferSchema = True
)

# Primer contacto con delta: Crear la salida incial del DF con el log

Flight_csv.write.format("delta").save("/content/drive/MyDrive/flight_delta")

# Lectura ya usando delta

Flight_delta = spark.read.format("delta").load("/content/drive/MyDrive/flight_delta")

# Particiones con delta

## Ejercicio, particionar por tipo de país

(
    Flight_delta.write
                .partitionBy("from_country")
                .format("delta")
                .save("/content/drive/MyDrive/flight_delta2")
)

# Revisar historial

from delta.tables import DeltaTable

deltaTable = DeltaTable.forPath(
    spark,
    "/content/drive/MyDrive/flight_delta"
)

deltaTable.history().show(truncate=False)

