# -*- coding: utf-8 -*-
"""S18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13C3BQmvemJbuIRq0_I1cqC0RHFT12qCT
"""

# Modulos a trabajar

from pyspark.sql import SparkSession
from pyspark.sql.functions import *

from pyspark.ml.feature import (
    StringIndexer,
    VectorAssembler,
    OneHotEncoder
)

from pyspark.ml.classification import DecisionTreeClassifier

from pyspark.ml import Pipeline

from pyspark.ml.evaluation import (
    BinaryClassificationEvaluator,
    MulticlassClassificationEvaluator
)

from pyspark.ml.functions import vector_to_array

# Crear sesión de Spark

spark = (
    SparkSession
    .builder
    .appName("DecisionTree")
    .getOrCreate()
)

# Lectura de datos

Partidos = spark.read.parquet(
    "/content/drive/MyDrive/partidos.parquet"
)

# Contar el total de filas

Partidos.count()

# Mostar una muestra de 25 datos

Partidos.show(25, truncate=False)

# Filtrar datos

shots = (
    Partidos
    .filter(col("`type.name`")=="Shot")
)

print("Número de disparos:", shots.count())

# Variable de respuesta

shots = shots.withColumn(
    "goal",
    when(
        col("`shot.outcome.name`") == "Goal",
        1
    ).otherwise(0)
)

# Coordenadas

shots = (
    shots
    .withColumn("x", col("location")[0])
    .withColumn("y", col("location")[1])
)

# Distancia

shots = shots.withColumn(
    "distance",
    sqrt(
        pow(120-col("x"),2) +
        pow(40-col("y"),2)
    )
)

# Distancia al centro

shots = (
    shots
    .withColumn("y_center",
                abs(col("y")-40))
)

# Ángulo apróximado

shots = shots.withColumn(
    "angle",
    atan(
        lit(7.32)/col("distance")
    )
)

# Variables binarias

shots = shots.withColumn(
    "pressure",
    when(col("under_pressure")==True,1).otherwise(0)
)

shots = shots.withColumn(
    "first_time",
    when(col("`shot.first_time`")==True,1).otherwise(0)
)

shots = shots.withColumn(
    "one_on_one",
    when(col("`shot.one_on_one`")==True,1).otherwise(0)
)

shots = shots.withColumn(
    "open_goal",
    when(col("`shot.open_goal`")==True,1).otherwise(0)
)

# Limpieza de observaciones sin ubicación

shots = shots.dropna(
    subset=[
        "x",
        "y",
        "distance",
        "angle"
    ]
)

shots.count()

# Selección de variables para el modelo

modelo_df = (
    shots.select(
        "goal",
        "`player.name`",
        "`team.name`",
        "minute",
        "distance",
        "angle",
        "x",
        "y",
        "pressure",
        "first_time",
        "one_on_one",
        "open_goal",
        "`shot.body_part.name`",
        "`shot.technique.name`",
        "`play_pattern.name`"
    )
    .withColumnRenamed("player.name", "player")
    .withColumnRenamed("team.name", "team")
    .withColumnRenamed("shot.body_part.name", "body_part")
    .withColumnRenamed("shot.technique.name", "technique")
    .withColumnRenamed("play_pattern.name", "play_pattern")
)

modelo_df.show()

# Variables categoricas

body_indexer = StringIndexer(
    inputCol="body_part",
    outputCol="body_index",
    handleInvalid="keep"
)

tech_indexer = StringIndexer(
    inputCol="technique",
    outputCol="tech_index",
    handleInvalid="keep"
)

pattern_indexer = StringIndexer(
    inputCol="play_pattern",
    outputCol="pattern_index",
    handleInvalid="keep"
)

# One hot encoder

encoder = OneHotEncoder(
    inputCols=[
        "body_index",
        "tech_index",
        "pattern_index"
    ],
    outputCols=[
        "body_vec",
        "tech_vec",
        "pattern_vec"
    ]
)

# Asignar variables del modelo

assembler = VectorAssembler(
    inputCols=[
        "distance",
        "angle",
        "x",
        "y",
        "pressure",
        "first_time",
        "one_on_one",
        "open_goal",
        "body_vec",
        "tech_vec",
        "pattern_vec"
    ],
    outputCol="features"
)

# Arbol de decisión

dt = DecisionTreeClassifier(
    labelCol = "goal",
    featuresCol = "features",
    predictionCol="prediccion",
    probabilityCol = "probability",
    maxDepth=8,
    minInstancesPerNode = 20,
    impurity="gini",
    seed = 123
)

# Pipeline

pipeline = Pipeline(
    stages = [
        body_indexer,
        tech_indexer,
        pattern_indexer,
        encoder,
        assembler,
        dt
    ]
)

# Train / Test

train, test = modelo_df.randomSplit(
    [0.80, 0.20],
    seed=123
)

# Entrenamiento de Árbol de decisión

model = pipeline.fit(train)

# Predicciones

pred = model.transform(test)

# Probabilidades de gol

pred = pred.withColumn(
    "xG",
    vector_to_array(col("probability"))[1]
)

# Resultados

pred.show()

# Métricas

from pyspark.ml.evaluation import (
    BinaryClassificationEvaluator,
    MulticlassClassificationEvaluator
)

auc = BinaryClassificationEvaluator(
    labelCol="goal",
    metricName="areaUnderROC"
).evaluate(pred)

accuracy = MulticlassClassificationEvaluator(
    labelCol="goal",
    predictionCol="prediccion",
    metricName="accuracy"
).evaluate(pred)

precision = MulticlassClassificationEvaluator(
    labelCol="goal",
    predictionCol="prediccion",
    metricName="weightedPrecision"
).evaluate(pred)

recall = MulticlassClassificationEvaluator(
    labelCol="goal",
    predictionCol="prediccion",
    metricName="weightedRecall"
).evaluate(pred)

f1 = MulticlassClassificationEvaluator(
    labelCol="goal",
    predictionCol="prediccion",
    metricName="f1"
).evaluate(pred)

# Imprimir métricas del modelo

print("\n")
print("="*60)
print("RESULTADOS DEL MODELO")
print("="*60)

print(f"AUC ROC   : {auc:.4f}")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

body_model = model.stages[0]
print(body_model.labels)

teach_model = model.stages[1]
print(teach_model.labels)

pattern_model = model.stages[2]
print(pattern_model.labels)

"""|Número|Variable|
|------|--------|
|distance|0|
|angle|1|
|x|2|
|y|3|
|pressure|4|
|first_time|5|
|one_on_one|6|
|open_goal|7|
|Right Foot|8|
|Left Foot|9|
|Head|10|
|Other|11|
|Normal|12|
|Half Volley|13|
|Volley|14|
|Lob|15|
|Overhead Kick|16|
|Backheel|17|
|Diving Header|18|
|Regular Play|19|
|From Free Kick|20|
|From Throw In|21|
|From Corner|22|
|From Counter|23|
|From Goal Kick|24|
|From Keeper|25|
|Other|26|
|From Kick Off|27|

"""

# Importancia de variables

tree = model.stages[-1]
print("\nImportancia de variables\n")
print(tree.featureImportances)

# Reglas del árbol

print(tree.toDebugString)

# Disparos con mayor probabilidad de gol

pred.select(
    "player",
    "team",
    "minute",
    "distance",
    "angle",
    "goal",
    "prediccion",
    "xG"
).orderBy(
    col("xG").desc()
).filter((col("goal")== 1) & (col("prediccion") ==1)).show(100, False)

# Guardar resultados

pred.select(
    "player",
    "team",
    "minute",
    "distance",
    "angle",
    "goal",
    "prediccion",
    "xG"
).orderBy(
    col("xG").desc()
).filter((col("goal")== 1) & (col("prediccion") ==1))\
.write.csv("/content/drive/MyDrive/Resultado_XG_DecisionTree.csv")

# Guardar el modelo

model.write()\
     .overwrite()\
     .save("/content/drive/MyDrive/modelo_XG_DecisionTree")